const fs = require("fs");
let src = fs.readFileSync("app/washstation/report/page.tsx", "utf8");

src = src.replace(
  "if (existingDraft) {\r\n      setAttendants(existingDraft.attendantsOnShift?.length ? existingDraft.attendantsOnShift : ['']);\r\n      setWasherTokens(existingDraft.washerTokensUsed ?? 0);\r\n      setDryerTokens(existingDraft.dryerTokensUsed ?? 0);\r\n      setCashAmount(existingDraft.cashAmount ?? 0);\r\n      setMobileMoneyAmount(existingDraft.mobileMoneylAmount ?? 0);\r\n      setCardAmount(existingDraft.cardAmount ?? 0);\r\n      setPaystackAmount(existingDraft.paystackAmount ?? 0);\r\n      setSoapUnits(existingDraft.soapUnitsUsed ?? 0);\r\n      setFreeWashCount(existingDraft.freeWashCount ?? 0);\r\n      setWashingPlanCount(existingDraft.washingPlanCount ?? 0);\r\n      setTechnicalFaults(existingDraft.technicalFaultCount ?? 0);\r\n      setFaultNotes(existingDraft.technicalFaultNotes ?? '');\r\n      setNotes(existingDraft.notes ?? '');\r\n      setServiceBreakdown(existingDraft.serviceBreakdown ?? []);\r\n      setLoaded(true);",
  "if (existingDraft) {\r\n      // Manual fields come from draft\r\n      setAttendants(existingDraft.attendantsOnShift?.length ? existingDraft.attendantsOnShift : ['']);\r\n      setSoapUnits(existingDraft.soapUnitsUsed ?? 0);\r\n      setWashingPlanCount(existingDraft.washingPlanCount ?? 0);\r\n      setTechnicalFaults(existingDraft.technicalFaultCount ?? 0);\r\n      setFaultNotes(existingDraft.technicalFaultNotes ?? '');\r\n      setNotes(existingDraft.notes ?? '');\r\n      // Tokens and payments always come from live system data\r\n      if (autoData) {\r\n        setWasherTokens(autoData.washerTokensUsed ?? 0);\r\n        setDryerTokens(autoData.dryerTokensUsed ?? 0);\r\n        setCashAmount(autoData.cashAmount ?? 0);\r\n        setMobileMoneyAmount(autoData.mobileMoneylAmount ?? 0);\r\n        setCardAmount(autoData.cardAmount ?? 0);\r\n        setPaystackAmount(autoData.paystackAmount ?? 0);\r\n        setFreeWashCount(autoData.freeWashCount ?? 0);\r\n        setServiceBreakdown(autoData.serviceBreakdown ?? []);\r\n      }\r\n      setLoaded(true);"
);

fs.writeFileSync("app/washstation/report/page.tsx", src, "utf8");
console.log("Fixed:", src.includes("Tokens and payments always come from live system data"));
